import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const translations = {
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.properties': 'Propiedades',
    'nav.services': 'Nuestros Servicios',
    'nav.about': 'Quiénes Somos',
    'nav.contact': 'Contacto',
    'nav.favorites': 'Favoritos',
    'nav.account': 'Mi Cuenta',
    'nav.contact_btn': 'Contactar',
    
    // Home page
    'hero.title': 'Encuentra tu',
    'hero.title_highlight': 'Hogar Perfecto',
    'hero.subtitle': 'Miles de propiedades en alquiler y venta te esperan. Descubre tu próximo hogar con nosotros.',
    
    // Search form
    'search.location_placeholder': '¿Dónde buscas?',
    'search.property_type': 'Tipo de propiedad',
    'search.property_type_any': 'Cualquiera',
    'search.property_type_apartment': 'Apartamento',
    'search.property_type_house': 'Casa',
    'search.property_type_loft': 'Loft',
    'search.property_type_studio': 'Estudio',
    'search.operation': 'Alquiler o Venta',
    'search.operation_any': 'Cualquiera',
    'search.operation_rent': 'Alquiler',
    'search.operation_sale': 'Venta',
    'search.managed_by': 'Gestionada por',
    'search.managed_by_any': 'Cualquiera',
    'search.managed_by_nazari': 'Nazarí Homes',
    'search.managed_by_other': 'Otras Inmobiliarias',
    'search.search_btn': 'Buscar',
    'search.location': 'Ubicación',
    'search.type': 'Tipo de Propiedad',
    'search.type_all': 'Todos los tipos',
    'search.type_villa': 'Villa',
    'search.type_penthouse': 'Ático',
    'search.type_townhouse': 'Casa adosada',
    'search.price': 'Precio',
    'search.price_all': 'Cualquier precio',
    'search.bedrooms': 'Dormitorios',
    'search.bedrooms_all': 'Cualquier número',
    'search.clear_btn': 'Limpiar filtros',
    
    // Location search
    'location.search_text': 'Buscar por texto',
    'location.search_location': 'Buscar por ubicación',
    'location.search_by_location': 'Buscar por ubicación',
    'location.search_address': 'Buscar dirección',
    'location.address_placeholder': 'Escribe una dirección (ej: Jaén, Madrid Centro, Sevilla...)',
    'location.search_radius': 'Radio de búsqueda',
    'location.radius_500m': '500 metros',
    'location.radius_1km': '1 kilómetro',
    'location.radius_2km': '2 kilómetros',
    'location.radius_5km': '5 kilómetros',
    'location.radius_10km': '10 kilómetros',
    'location.radius_10km_plus': '10km+',
    'location.my_location': 'Mi Ubicación',
    'location.apply_location': 'Aplicar Ubicación',
    
    // Properties page translations
    'properties.page_title': 'Propiedades Encontradas',
    'properties.search_placeholder': 'Buscar por ubicación, tipo de propiedad...',
    'properties.operation_all': 'Todas',
    'properties.operation_rent': 'Alquiler',
    'properties.operation_sale': 'Venta',
    'properties.type_all': 'Todos',
    'properties.type_apartment': 'Apartamento',
    'properties.type_house': 'Casa',
    'properties.type_loft': 'Loft',
    'properties.type_studio': 'Estudio',
    'properties.managed_all': 'Todas',
    'properties.managed_nazari': 'Nazarí Homes',
    'properties.managed_other': 'Otras Inmobiliarias',
    'properties.filters': 'Filtros',
    'properties.price_range': 'Rango de Precio (€)',
    'properties.min_bedrooms': 'Habitaciones mínimas',
    'properties.min_bathrooms': 'Baños mínimos',
    'properties.features': 'Características',
    'properties.heating': 'Calefacción',
    'properties.pool': 'Piscina',
    'properties.garage': 'Garaje',
    'properties.air_conditioning': 'Aire Acondicionado',
    'properties.elevator': 'Ascensor',
    'properties.terrace': 'Terraza/Balcón',
    'properties.garden': 'Jardín',
    'properties.results_subtitle': 'Resultados de tu búsqueda',
    'properties.no_results_title': 'No se encontraron propiedades',
    'properties.no_results_desc': 'Prueba ajustando los filtros de búsqueda para encontrar más resultados.',
    'properties.any': 'Cualquiera',
    'properties.bedrooms_unit': 'hab.',
    'properties.bathrooms_unit': 'baños',
    'properties.area_unit': 'm²',
    'properties.per_month': '/mes',
    'properties.view_details': 'Ver Detalles',
    'properties.search_results': 'Resultados de Búsqueda',
    'properties.featured': 'Propiedades Destacadas',
    'properties.search_results_desc': 'Encontradas {count} propiedades que coinciden con tu búsqueda',
    'properties.featured_desc': 'Descubre nuestra selección de las mejores propiedades disponibles',
    'properties.show_featured': 'Ver Propiedades Destacadas',
    'properties.no_results': 'No se encontraron propiedades que coincidan con tu búsqueda',
    'properties.view_all': 'Ver Todas las Propiedades',
    'properties.latest': 'Últimas Propiedades',
    'properties.more': 'más',
    
    // Statistics
    'stats.properties': 'Propiedades Disponibles',
    'stats.clients': 'Clientes Satisfechos',
    'stats.success_rate': 'Tasa de Éxito',
    
    // Property details
    'property.bedrooms': 'dormitorios',
    'property.bathrooms': 'baños',
    'property.area': 'm²',
    'property.view_details': 'Ver detalles',
    
    // Services page translations
    'services.title': 'Nuestros',
    'services.title_highlight': 'Servicios',
    'services.subtitle': 'Ofrecemos una gama completa de servicios inmobiliarios para hacer que tu experiencia sea perfecta',
    'services.what_can_we_do': '¿Qué Podemos Hacer por Ti?',
    'services.what_can_we_do_desc': 'Desde la gestión completa hasta servicios específicos, adaptamos nuestros servicios a tus necesidades',
    'services.management.title': 'Gestión Inmobiliaria Integral',
    'services.management.description': 'Administramos tu propiedad de manera completa, desde el marketing hasta la entrega de llaves.',
    'services.management.feature1': 'Marketing profesional',
    'services.management.feature2': 'Selección de inquilinos',
    'services.management.feature3': 'Gestión de contratos',
    'services.management.feature4': 'Mantenimiento',
    'services.rental.title': 'Alquiler y Venta',
    'services.rental.description': 'Servicios especializados tanto para alquiler como venta de propiedades residenciales y comerciales.',
    'services.rental.feature1': 'Valoración gratuita',
    'services.rental.feature2': 'Fotografía profesional',
    'services.rental.feature3': 'Publicación en portales',
    'services.rental.feature4': 'Visitas guiadas',
    'services.legal.title': 'Asesoramiento Legal',
    'services.legal.description': 'Te acompañamos en todos los aspectos legales de tu transacción inmobiliaria.',
    'services.legal.feature1': 'Revisión de contratos',
    'services.legal.feature2': 'Gestión de documentos',
    'services.legal.feature3': 'Asesoría fiscal',
    'services.legal.feature4': 'Tramitación legal',
    'services.support.title': 'Atención 24/7',
    'services.support.description': 'Nuestro equipo está disponible para resolver cualquier incidencia en cualquier momento.',
    'services.support.feature1': 'Soporte continuo',
    'services.support.feature2': 'Emergencias',
    'services.support.feature3': 'Comunicación directa',
    'services.support.feature4': 'Respuesta inmediata',
    'services.tenants.title': 'Gestión de Inquilinos',
    'services.tenants.description': 'Nos encargamos de toda la relación con los inquilinos para que no tengas que preocuparte.',
    'services.tenants.feature1': 'Selección rigurosa',
    'services.tenants.feature2': 'Cobro de rentas',
    'services.tenants.feature3': 'Resolución de incidencias',
    'services.tenants.feature4': 'Comunicación directa',
    'services.maintenance.title': 'Mantenimiento y Reformas',
    'services.maintenance.description': 'Mantenemos tu propiedad en perfecto estado con nuestro equipo de profesionales.',
    'services.maintenance.feature1': 'Mantenimiento preventivo',
    'services.maintenance.feature2': 'Reparaciones urgentes',
    'services.maintenance.feature3': 'Reformas integrales',
    'services.maintenance.feature4': 'Control de calidad',
    'services.cta.title': '¿Listo para Empezar?',
    'services.cta.description': 'Contacta con nosotros y descubre cómo podemos ayudarte con tu propiedad',
    'services.cta.contact_now': 'Contactar Ahora',
    'services.cta.call_directly': 'Llamar Directamente',
    
    // About page translations
    'about.title': 'Quiénes',
    'about.title_highlight': 'Somos',
    'about.subtitle': 'Más de 15 años ayudando a encontrar el hogar perfecto en Granada y toda Andalucía',
    'about.our_story': 'Nuestra Historia',
    'about.story_p1': 'Nazarí Homes nació en 2009 con una visión clara: revolucionar el sector inmobiliario en Granada ofreciendo un servicio personalizado, transparente y de máxima calidad. Comenzamos como una pequeña empresa familiar y hemos crecido hasta convertirnos en una de las inmobiliarias de referencia en Andalucía.',
    'about.story_p2': 'Nuestro nombre rinde homenaje al Reino Nazarí de Granada, reflejando nuestro profundo amor por esta ciudad y nuestro compromiso con su patrimonio arquitectónico y cultural. Cada propiedad que gestionamos es tratada con el mismo cuidado y atención al detalle que caracterizaba a los maestros constructores nazaríes.',
    'about.stats.years': 'Años de Experiencia',
    'about.stats.properties': 'Propiedades Gestionadas',
    'about.stats.clients': 'Clientes Satisfechos',
    'about.stats.satisfaction': 'Tasa de Satisfacción',
    'about.our_values': 'Nuestros Valores',
    'about.values_desc': 'Los principios que guían cada una de nuestras acciones y decisiones',
    'about.commitment.title': 'Compromiso',
    'about.commitment.description': 'Nos comprometemos al 100% con cada cliente y cada propiedad que gestionamos.',
    'about.professionalism.title': 'Profesionalidad',
    'about.professionalism.description': 'Aplicamos los más altos estándares de calidad en todos nuestros servicios.',
    'about.trust.title': 'Confianza',
    'about.trust.description': 'Construimos relaciones duraderas basadas en la transparencia y honestidad.',
    'about.excellence.title': 'Excelencia',
    'about.excellence.description': 'Buscamos la excelencia en cada detalle para superar las expectativas.',
    'about.our_team': 'Nuestro Equipo',
    'about.team_desc': 'Profesionales apasionados por el sector inmobiliario',
    'about.sales_team.title': 'Equipo Comercial',
    'about.sales_team.description': 'Nuestros agentes comerciales tienen años de experiencia en el mercado local y conocen cada barrio de Granada como la palma de su mano.',
    'about.management_team.title': 'Equipo de Gestión',
    'about.management_team.description': 'Nuestro equipo de gestión se encarga de que todo funcione perfectamente, desde el mantenimiento hasta la atención al cliente.',
    'about.cta.title': '¿Quieres Conocernos Mejor?',
    'about.cta.description': 'Ven a visitarnos a nuestra oficina en Granada o contacta con nosotros',
    'about.cta.contact': 'Contactar',
    'about.cta.address': 'Calle Real de la Alhambra, 15 - Granada',
    
    // Footer translations
    'footer.company_description': 'Tu partner de confianza para encontrar la propiedad perfecta. Más de 10 años de experiencia en el sector inmobiliario.',
    'footer.quick_links': 'Enlaces Rápidos',
    'footer.services_section': 'Servicios',
    'footer.rental_properties': 'Alquiler de Propiedades',
    'footer.sale_properties': 'Venta de Propiedades',
    'footer.free_valuation': 'Tasación Gratuita',
    'footer.legal_advice': 'Asesoría Legal',
    'footer.contact_section': 'Contacto',
    'footer.address': 'Calle Gran Vía 123, Madrid',
    'footer.phone': '+34 91 123 45 67',
    'footer.email': 'nazarihomesgranada@gmail.com',
    'footer.copyright': '© 2025 Nazarí Homes. Todos los derechos reservados.',
    
    // Contact, Favorites, and Common translations
    'contact.title': 'Contacto',
    'contact.subtitle': 'Estamos aquí para ayudarte con todas tus necesidades inmobiliarias',
    'contact.operation_area': 'Nuestra zona de operación en Granada',
    'contact.whatsapp_text': '¡Escríbenos por WhatsApp!',
    'contact.operation_zone': 'Zona de actuación:',
    'contact.granada_province': 'Granada y provincia',
    'contact.no_physical_office': '*Trabajamos por toda Granada sin oficina física',
    'contact.form_title': 'Deja tus datos y te llamamos',
    'contact.form_subtitle': '¡Obtenga tu valoración gratuita sin compromiso!',
    'contact.property_address': 'Dirección del inmueble',
    'contact.name': 'Nombre',
    'contact.surname': 'Apellidos',
    'contact.email': 'Correo electrónico',
    'contact.phone': 'Teléfono',
    'contact.message': 'Mensaje (opcional)',
    'contact.privacy_text': 'He leído y acepto la',
    'contact.privacy_policy': 'Política de privacidad',
    'contact.privacy_error': 'Debes aceptar la política de privacidad para enviar el formulario.',
    'contact.send_button': 'Enviar',
    'contact.form_sent': 'Formulario enviado',
    'contact.form_sent_desc': 'Te contactaremos pronto. ¡Gracias por tu interés!',
    'contact.whatsapp_message': 'Hola, me gustaría información sobre sus servicios inmobiliarios.',
    
    'favorites.title': 'Mis Favoritos',
    'favorites.clear_all': 'Eliminar todos',
    'favorites.confirm_clear_title': '¿Eliminar todos los favoritos?',
    'favorites.confirm_clear_desc': 'Esta acción eliminará todas las propiedades de tu lista de favoritos. Esta acción no se puede deshacer.',
    'favorites.cancel': 'Cancelar',
    'favorites.delete_all': 'Eliminar todos',
    'favorites.no_favorites': 'No tienes propiedades guardadas como favoritas aún.',
    'favorites.count_single': 'Has guardado 1 propiedad como favorita.',
    'favorites.count_multiple': 'Has guardado {count} propiedades como favoritas.',
    'favorites.empty_title': 'No hay favoritos guardados',
    'favorites.empty_desc': 'Empieza a explorar propiedades y marca las que te gusten como favoritas.',
    
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.language': 'Idioma:',
    'common.search': 'Buscar',
    'common.cancel': 'Cancelar',

    // Property detail page translations
    'property.not_found': 'Propiedad no encontrada',
    'property.back_to_properties': 'Volver a Propiedades',
    'property.view_number': 'Vista {number}',
    'property.reference': 'Ref',
    'property.bedrooms': 'Habitaciones',
    'property.bathrooms': 'Baños',
    'property.area_label': 'Superficie',
    'property.parking': 'Parking',
    'property.description': 'Descripción',
    'property.location': 'Ubicación',
    'property.area_info': 'Información de la zona',
    'property.area_description': 'Excelente ubicación en una zona residencial tranquila, cerca de transporte público, centros comerciales y servicios básicos. Fácil acceso a las principales vías de comunicación.',
    'property.features': 'Características',
    'property.elevator': 'Ascensor',
    'property.balcony': 'Balcón',
    'property.heating': 'Calefacción',
    'property.terrace': 'Terraza',
    'property.built_in_wardrobes': 'Armarios empotrados',
    'property.equipped_kitchen': 'Cocina equipada',
    'property.services': 'Servicios',
    'property.wifi': 'WiFi',
    'property.air_conditioning': 'Aire Acondicionado',
    'property.tv': 'TV',
    'property.additional_info': 'Información Adicional',
    'property.transport': 'Transporte',
    'property.transport_description': 'A 5 minutos caminando de la estación de metro. Múltiples líneas de autobús cercanas. Fácil acceso a las principales vías de comunicación.',
    'property.neighborhood': 'Zona',
    'property.neighborhood_description': 'Barrio familiar con colegios, parques, centros de salud y comercios en los alrededores. Ambiente seguro y tranquilo ideal para familias.',
    'property.nearby_services': 'Servicios cercanos',
    'property.nearby_services_description': 'Supermercados, farmacias, restaurantes y cafeterías en un radio de 300 metros. Centro médico y biblioteca municipal a 10 minutos a pie.',
    'property.real_estate_agent': 'Agente Inmobiliario',
    'property.senior_agent': 'Agente Senior',
    'property.call': 'Llamar',
    'property.appointment': 'Cita',
    'property.whatsapp_chat': 'Chat WhatsApp',
    'property.whatsapp_description': 'Chatea directamente con {agency} para agendar una cita o resolver tus dudas al instante.',
    'property.quick_messages': 'Mensajes rápidos',
    'property.custom_message_placeholder': 'Escribe tu mensaje personalizado...',
    'property.open_whatsapp': 'Abrir WhatsApp',
    'property.quick_response': 'Te responderemos en menos de 5 minutos',
    'property.reserve_property': 'Reservar Propiedad',
    'property.reservation_description': 'Completa el formulario y adjunta el contrato firmado para proceder con la reserva.',
    'property.full_name': 'Nombre completo',
    'property.full_name_placeholder': 'Nombre y apellidos',
    'property.email_placeholder': 'correo@ejemplo.com',
    'property.phone_placeholder': '+34 600 000 000',
    'property.dni_nie': 'DNI/NIE',
    'property.dni_placeholder': '12345678A',
    'property.signed_contract': 'Contrato firmado',
    'property.change_pdf': 'Cambiar archivo PDF',
    'property.upload_contract': 'Subir contrato firmado',
    'property.proceed_payment': 'Proceder al Pago',
    'property.secure_payment': 'Pago seguro • Reserva inmediata • Confirmación por email',
    'property.request_info': 'Solicitar Información',
    'property.send_inquiry': 'Enviar Consulta',
    'property.per_month': '/mes',
    
    // Property type descriptions
    'property.apartment_description': 'Hermoso apartamento ubicado en una zona privilegiada. Completamente renovado con acabados de alta calidad y todas las comodidades modernas.',
    'property.house_description': 'Magnífica casa familiar perfecta para disfrutar en familia. Espacios amplios y bien distribuidos con múltiples opciones de entretenimiento.',
    'property.loft_description': 'Impresionante loft de estilo moderno con espacios diáfanos y una decoración contemporánea que combina funcionalidad y estilo.',
    'property.studio_description': 'Acogedor estudio completamente reformado y con mucha luz natural. Perfecto para jóvenes profesionales o estudiantes.',
    'property.default_description': 'Excelente propiedad en ubicación privilegiada.',
    
    // WhatsApp messages
    'property.whatsapp_default_message': 'Hola! Estoy interesado en la propiedad "{title}" (Ref: {reference}) ubicada en {location}. {price}. Me gustaría agendar una cita para visitarla.',
    'property.quick_message_visit': 'Quiero agendar una visita para la propiedad "{title}" Ref: {reference} en {location}',
    'property.quick_message_available': '¿Está disponible la propiedad Ref: {reference} por {price}?',
    'property.quick_message_schedule': '¿Cuáles son los horarios de visita para la propiedad Ref: {reference} en {location}?',
    'property.quick_message_price_info': 'Necesito más información sobre el precio de {price} para la propiedad Ref: {reference}',
  },
  en: {
    // Header translations
    'nav.home': 'Home',
    'nav.properties': 'Properties',
    'nav.services': 'Our Services',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.favorites': 'Favorites',
    'nav.account': 'My Account',
    'nav.contact_btn': 'Contact',
    
    // Home page translations
    'hero.title': 'Find your',
    'hero.title_highlight': 'Perfect Home',
    'hero.subtitle': 'Thousands of rental and sale properties await you. Discover your next home with us.',
    
    // Search form translations
    'search.location_placeholder': 'Where are you looking?',
    'search.property_type': 'Property Type',
    'search.property_type_any': 'Any',
    'search.property_type_apartment': 'Apartment',
    'search.property_type_house': 'House',
    'search.property_type_loft': 'Loft',
    'search.property_type_studio': 'Studio',
    'search.operation': 'Rent or Sale',
    'search.operation_any': 'Any',
    'search.operation_rent': 'Rent',
    'search.operation_sale': 'Sale',
    'search.managed_by': 'Managed by',
    'search.managed_by_any': 'Any',
    'search.managed_by_nazari': 'Nazarí Homes',
    'search.managed_by_other': 'Other Agencies',
    'search.search_btn': 'Search',
    'search.location': 'Location',
    'search.type': 'Property Type',
    'search.type_all': 'All types',
    'search.type_villa': 'Villa',
    'search.type_penthouse': 'Penthouse',
    'search.type_townhouse': 'Townhouse',
    'search.price': 'Price',
    'search.price_all': 'Any price',
    'search.bedrooms': 'Bedrooms',
    'search.bedrooms_all': 'Any number',
    'search.clear_btn': 'Clear filters',
    
    // Location search
    'location.search_text': 'Search by text',
    'location.search_location': 'Search by location',
    'location.search_by_location': 'Search by location',
    'location.search_address': 'Search address',
    'location.address_placeholder': 'Enter an address (e.g.: Madrid, Barcelona, Seville...)',
    'location.search_radius': 'Search radius',
    'location.radius_500m': '500 meters',
    'location.radius_1km': '1 kilometer',
    'location.radius_2km': '2 kilometers',
    'location.radius_5km': '5 kilometers',
    'location.radius_10km': '10 kilometers',
    'location.radius_10km_plus': '10km+',
    'location.my_location': 'My Location',
    'location.apply_location': 'Apply Location',
    
    // Properties page translations
    'properties.page_title': 'Properties Found',
    'properties.search_placeholder': 'Search by location, property type...',
    'properties.operation_all': 'All',
    'properties.operation_rent': 'Rent',
    'properties.operation_sale': 'Sale',
    'properties.type_all': 'All',
    'properties.type_apartment': 'Apartment',
    'properties.type_house': 'House',
    'properties.type_loft': 'Loft',
    'properties.type_studio': 'Studio',
    'properties.managed_all': 'All',
    'properties.managed_nazari': 'Nazarí Homes',
    'properties.managed_other': 'Other Agencies',
    'properties.filters': 'Filters',
    'properties.price_range': 'Price Range (€)',
    'properties.min_bedrooms': 'Minimum bedrooms',
    'properties.min_bathrooms': 'Minimum bathrooms',
    'properties.features': 'Features',
    'properties.heating': 'Heating',
    'properties.pool': 'Pool',
    'properties.garage': 'Garage',
    'properties.air_conditioning': 'Air Conditioning',
    'properties.elevator': 'Elevator',
    'properties.terrace': 'Terrace/Balcony',
    'properties.garden': 'Garden',
    'properties.results_subtitle': 'Search results',
    'properties.no_results_title': 'No properties found',
    'properties.no_results_desc': 'Try adjusting your search filters to find more results.',
    'properties.any': 'Any',
    'properties.bedrooms_unit': 'bed.',
    'properties.bathrooms_unit': 'baths',
    'properties.area_unit': 'm²',
    'properties.per_month': '/month',
    'properties.view_details': 'View Details',
    'properties.search_results': 'Search Results',
    'properties.featured': 'Featured Properties',
    'properties.search_results_desc': 'Found {count} properties matching your search',
    'properties.featured_desc': 'Discover our selection of the best available properties',
    'properties.show_featured': 'View Featured Properties',
    'properties.no_results': 'No properties found matching your search',
    'properties.view_all': 'View All Properties',
    'properties.latest': 'Latest Properties',
    'properties.more': 'more',

    // Statistics
    'stats.properties': 'Available Properties',
    'stats.clients': 'Satisfied Clients',
    'stats.success_rate': 'Success Rate',
    
    // Property details
    'property.bedrooms': 'bedrooms',
    'property.bathrooms': 'bathrooms',
    'property.area': 'm²',
    'property.view_details': 'View details',
    
    // Services, About, Footer, Contact, Favorites, and Common translations
    'services.title': 'Our',
    'services.title_highlight': 'Services',
    'services.subtitle': 'We offer a complete range of real estate services to make your experience perfect',
    'services.what_can_we_do': 'What We Can Do for You?',
    'services.what_can_we_do_desc': 'From complete management to specific services, we adapt our services to your needs',
    'services.management.title': 'Comprehensive Property Management',
    'services.management.description': 'We manage your property completely, from marketing to key handover.',
    'services.management.feature1': 'Professional marketing',
    'services.management.feature2': 'Tenant selection',
    'services.management.feature3': 'Contract management',
    'services.management.feature4': 'Maintenance',
    'services.rental.title': 'Rental and Sales',
    'services.rental.description': 'Specialized services for both rental and sale of residential and commercial properties.',
    'services.rental.feature1': 'Free valuation',
    'services.rental.feature2': 'Professional photography',
    'services.rental.feature3': 'Portal publication',
    'services.rental.feature4': 'Guided tours',
    'services.legal.title': 'Legal Advisory',
    'services.legal.description': 'We accompany you in all legal aspects of your real estate transaction.',
    'services.legal.feature1': 'Contract review',
    'services.legal.feature2': 'Document management',
    'services.legal.feature3': 'Tax advisory',
    'services.legal.feature4': 'Legal processing',
    'services.support.title': '24/7 Support',
    'services.support.description': 'Our team is available to resolve any issue at any time.',
    'services.support.feature1': 'Continuous support',
    'services.support.feature2': 'Emergencies',
    'services.support.feature3': 'Direct communication',
    'services.support.feature4': 'Immediate response',
    'services.tenants.title': 'Tenant Management',
    'services.tenants.description': 'We take care of the entire relationship with tenants so you don\'t have to worry.',
    'services.tenants.feature1': 'Rigorous selection',
    'services.tenants.feature2': 'Rent collection',
    'services.tenants.feature3': 'Issue resolution',
    'services.tenants.feature4': 'Direct communication',
    'services.maintenance.title': 'Maintenance and Renovations',
    'services.maintenance.description': 'We keep your property in perfect condition with our team of professionals.',
    'services.maintenance.feature1': 'Preventive maintenance',
    'services.maintenance.feature2': 'Emergency repairs',
    'services.maintenance.feature3': 'Complete renovations',
    'services.maintenance.feature4': 'Quality control',
    'services.cta.title': 'Ready to Get Started?',
    'services.cta.description': 'Contact us and discover how we can help you with your property',
    'services.cta.contact_now': 'Contact Now',
    'services.cta.call_directly': 'Call Directly',
    
    'about.title': 'About',
    'about.title_highlight': 'Us',
    'about.subtitle': 'Over 15 years helping to find the perfect home in Granada and all of Andalusia',
    'about.our_story': 'Our Story',
    'about.story_p1': 'Nazarí Homes was born in 2009 with a clear vision: to revolutionize the real estate sector in Granada by offering personalized, transparent and maximum quality service. We started as a small family business and have grown to become one of the reference real estate agencies in Andalusia.',
    'about.story_p2': 'Our name pays tribute to the Nasrid Kingdom of Granada, reflecting our deep love for this city and our commitment to its architectural and cultural heritage. Each property we manage is treated with the same care and attention to detail that characterized the Nasrid master builders.',
    'about.stats.years': 'Years of Experience',
    'about.stats.properties': 'Properties Managed',
    'about.stats.clients': 'Satisfied Clients',
    'about.stats.satisfaction': 'Satisfaction Rate',
    'about.our_values': 'Our Values',
    'about.values_desc': 'The principles that guide each of our actions and decisions',
    'about.commitment.title': 'Commitment',
    'about.commitment.description': 'We commit 100% to each client and each property we manage.',
    'about.professionalism.title': 'Professionalism',
    'about.professionalism.description': 'We apply the highest quality standards in all our services.',
    'about.trust.title': 'Trust',
    'about.trust.description': 'We build lasting relationships based on transparency and honesty.',
    'about.excellence.title': 'Excellence',
    'about.excellence.description': 'We seek excellence in every detail to exceed expectations.',
    'about.our_team': 'Our Team',
    'about.team_desc': 'Professionals passionate about real estate',
    'about.sales_team.title': 'Sales Team',
    'about.sales_team.description': 'Our sales agents have years of experience in the local market and know every neighborhood in Granada like the back of their hand.',
    'about.management_team.title': 'Management Team',
    'about.management_team.description': 'Our management team ensures everything runs perfectly, from maintenance to customer service.',
    'about.cta.title': 'Want to Know Us Better?',
    'about.cta.description': 'Come visit us at our office in Granada or contact us',
    'about.cta.contact': 'Contact',
    'about.cta.address': 'Calle Real de la Alhambra, 15 - Granada',
    
    'footer.company_description': 'Your trusted partner to find the perfect property. Over 10 years of experience in the real estate sector.',
    'footer.quick_links': 'Quick Links',
    'footer.services_section': 'Services',
    'footer.rental_properties': 'Property Rentals',
    'footer.sale_properties': 'Property Sales',
    'footer.free_valuation': 'Free Valuation',
    'footer.legal_advice': 'Legal Advisory',
    'footer.contact_section': 'Contact',
    'footer.address': 'Gran Vía Street 123, Madrid',
    'footer.phone': '+34 91 123 45 67',
    'footer.email': 'nazarihomesgranada@gmail.com',
    'footer.copyright': '© 2025 Nazarí Homes. All rights reserved.',
    
    'contact.title': 'Contact',
    'contact.subtitle': 'We are here to help you with all your real estate needs',
    'contact.operation_area': 'Our operation area in Granada',
    'contact.whatsapp_text': 'Write to us on WhatsApp!',
    'contact.operation_zone': 'Operation area:',
    'contact.granada_province': 'Granada and province',
    'contact.no_physical_office': '*We work throughout Granada without a physical office',
    'contact.form_title': 'Leave your details and we will call you',
    'contact.form_subtitle': 'Get your free valuation without commitment!',
    'contact.property_address': 'Property address',
    'contact.name': 'Name',
    'contact.surname': 'Surname',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message (optional)',
    'contact.privacy_text': 'I have read and accept the',
    'contact.privacy_policy': 'Privacy Policy',
    'contact.privacy_error': 'You must accept the privacy policy to send the form.',
    'contact.send_button': 'Send',
    'contact.form_sent': 'Form sent',
    'contact.form_sent_desc': 'We will contact you soon. Thank you for your interest!',
    'contact.whatsapp_message': 'Hello, I would like information about your real estate services.',
    
    'favorites.title': 'My Favorites',
    'favorites.clear_all': 'Clear all',
    'favorites.confirm_clear_title': 'Clear all favorites?',
    'favorites.confirm_clear_desc': 'This action will remove all properties from your favorites list. This action cannot be undone.',
    'favorites.cancel': 'Cancel',
    'favorites.delete_all': 'Delete all',
    'favorites.no_favorites': 'You have no properties saved as favorites yet.',
    'favorites.count_single': 'You have saved 1 property as favorite.',
    'favorites.count_multiple': 'You have saved {count} properties as favorites.',
    'favorites.empty_title': 'No saved favorites',
    'favorites.empty_desc': 'Start exploring properties and mark the ones you like as favorites.',
    
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.language': 'Language:',
    'common.search': 'Search',
    'common.cancel': 'Cancel',

    // Property detail page translations
    'property.not_found': 'Property not found',
    'property.back_to_properties': 'Back to Properties',
    'property.view_number': 'View {number}',
    'property.reference': 'Ref',
    'property.bedrooms': 'Bedrooms',
    'property.bathrooms': 'Bathrooms',
    'property.area_label': 'Area',
    'property.parking': 'Parking',
    'property.description': 'Description',
    'property.location': 'Location',
    'property.area_info': 'Area information',
    'property.area_description': 'Excellent location in a quiet residential area, close to public transport, shopping centers and basic services. Easy access to main communication routes.',
    'property.features': 'Features',
    'property.elevator': 'Elevator',
    'property.balcony': 'Balcony',
    'property.heating': 'Heating',
    'property.terrace': 'Terrace',
    'property.built_in_wardrobes': 'Built-in wardrobes',
    'property.equipped_kitchen': 'Equipped kitchen',
    'property.services': 'Services',
    'property.wifi': 'WiFi',
    'property.air_conditioning': 'Air Conditioning',
    'property.tv': 'TV',
    'property.additional_info': 'Additional Information',
    'property.transport': 'Transport',
    'property.transport_description': '5 minutes walk from the metro station. Multiple nearby bus lines. Easy access to main communication routes.',
    'property.neighborhood': 'Neighborhood',
    'property.neighborhood_description': 'Family neighborhood with schools, parks, health centers and shops in the surroundings. Safe and quiet environment ideal for families.',
    'property.nearby_services': 'Nearby services',
    'property.nearby_services_description': 'Supermarkets, pharmacies, restaurants and cafes within a 300-meter radius. Medical center and municipal library 10 minutes walk away.',
    'property.real_estate_agent': 'Real Estate Agent',
    'property.senior_agent': 'Senior Agent',
    'property.call': 'Call',
    'property.appointment': 'Appointment',
    'property.whatsapp_chat': 'WhatsApp Chat',
    'property.whatsapp_description': 'Chat directly with {agency} to schedule an appointment or resolve your questions instantly.',
    'property.quick_messages': 'Quick messages',
    'property.custom_message_placeholder': 'Write your custom message...',
    'property.open_whatsapp': 'Open WhatsApp',
    'property.quick_response': 'We will respond in less than 5 minutes',
    'property.reserve_property': 'Reserve Property',
    'property.reservation_description': 'Complete the form and attach the signed contract to proceed with the reservation.',
    'property.full_name': 'Full name',
    'property.full_name_placeholder': 'Name and surname',
    'property.email_placeholder': 'email@example.com',
    'property.phone_placeholder': '+34 600 000 000',
    'property.dni_nie': 'DNI/NIE',
    'property.dni_placeholder': '12345678A',
    'property.signed_contract': 'Signed contract',
    'property.change_pdf': 'Change PDF file',
    'property.upload_contract': 'Upload signed contract',
    'property.proceed_payment': 'Proceed to Payment',
    'property.secure_payment': 'Secure payment • Immediate reservation • Email confirmation',
    'property.request_info': 'Request Information',
    'property.send_inquiry': 'Send Inquiry',
    'property.per_month': '/month',
    
    // Property type descriptions
    'property.apartment_description': 'Beautiful apartment located in a privileged area. Completely renovated with high quality finishes and all modern amenities.',
    'property.house_description': 'Magnificent family house perfect for enjoying with family. Spacious and well-distributed spaces with multiple entertainment options.',
    'property.loft_description': 'Impressive modern-style loft with open spaces and contemporary decoration that combines functionality and style.',
    'property.studio_description': 'Cozy studio completely renovated and with lots of natural light. Perfect for young professionals or students.',
    'property.default_description': 'Excellent property in privileged location.',
    
    // WhatsApp messages
    'property.whatsapp_default_message': 'Hello! I am interested in the property "{title}" (Ref: {reference}) located in {location}. {price}. I would like to schedule a visit.',
    'property.quick_message_visit': 'I want to schedule a visit for the property "{title}" Ref: {reference} in {location}',
    'property.quick_message_available': 'Is the property Ref: {reference} available for {price}?',
    'property.quick_message_schedule': 'What are the visiting hours for the property Ref: {reference} in {location}?',
    'property.quick_message_price_info': 'I need more information about the price of {price} for the property Ref: {reference}',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language]?.[key as keyof typeof translations[typeof language]] || key;
    
    // Simple parameter replacement
    if (params && typeof translation === 'string') {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
