import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es";

interface Translation {
  [key: string]: string | Translation;
}

interface Translations {
  [key: string]: Translation;
}

interface LanguageContextProps {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Translations = {
  es: {
    nav: {
      home: "Inicio",
      properties: "Propiedades",
      services: "Servicios",
      about: "Nosotros",
      contact: "Contacto",
      favorites: "Favoritos",
      account: "Cuenta",
    },
    common: {
      language: "Idioma",
      search: "Buscar",
      address: "Dirección",
      all: "Todos",
      bedrooms: "Habitaciones",
      bathrooms: "Baños",
      area: "Área",
      price: "Precio",
      applyFilters: "Aplicar filtros",
      resetFilters: "Restablecer filtros",
      loadMore: "Cargar más",
      noPropertiesFound: "No se encontraron propiedades con los criterios de búsqueda actuales.",
      details: "Detalles",
      description: "Descripción",
      amenities: "Comodidades",
      location: "Ubicación",
      contactUs: "Contáctanos",
      disclaimer: "Descargo de responsabilidad",
      disclaimerText:
        "La información sobre la propiedad se proporciona únicamente como guía y no constituye una oferta contractual. Todas las representaciones, incluidas las dimensiones, los detalles del plano y la disponibilidad, están sujetas a cambios y deben verificarse de forma independiente.",
      share: "Compartir",
      addToFavorites: "Añadir a favoritos",
      removeFromFavorites: "Eliminar de favoritos",
      relatedProperties: "Propiedades relacionadas",
      map: "Mapa",
      streetView: "Vista de calle",
      virtualTour: "Tour virtual",
      scheduleVisit: "Agendar visita",
      mortgageCalculator: "Calculadora de hipoteca",
      cancel: "Cancelar",
      back: "Volver",
    },
    hero: {
      title: "Tu hogar ideal con",
      title_highlight: "gestión integral",
      subtitle: "Compra, vende o alquila con total tranquilidad. Nos encargamos de todo por ti",
      searchPlaceholder: "¿Qué estás buscando?",
    },
    search: {
      location_placeholder: "Buscar por ubicación...",
      property_type: "Tipo de propiedad",
      property_type_any: "Cualquier tipo",
      property_type_apartment: "Apartamento",
      property_type_house: "Casa",
      property_type_loft: "Loft",
      property_type_studio: "Estudio",
      operation: "Operación",
      operation_any: "Cualquiera",
      operation_rent: "Alquiler",
      operation_sale: "Venta",
      managed_by: "Gestionado por",
      managed_by_any: "Cualquiera",
      managed_by_nazari: "Nazarí Homes",
      managed_by_other: "Otros",
      search_btn: "Buscar",
    },
    location: {
      search_text: "Buscar ubicación",
      search_location: "Buscar por ubicación",
      search_by_location: "Buscar por ubicación",
      search_address: "Dirección",
      address_placeholder: "Introduce una dirección...",
      search_radius: "Radio de búsqueda",
      radius_500m: "500 metros",
      radius_1km: "1 kilómetro",
      radius_2km: "2 kilómetros",
      radius_5km: "5 kilómetros",
      radius_10km: "10 kilómetros",
      radius_10km_plus: "10+ kilómetros",
      my_location: "Mi ubicación",
      apply_location: "Aplicar ubicación",
    },
    stats: {
      properties: "Propiedades disponibles",
      clients: "Clientes satisfechos",
      success_rate: "Tasa de éxito",
    },
    properties: {
      page_title: "propiedades encontradas",
      search_placeholder: "Buscar por título o ubicación...",
      results_subtitle: "Encuentra la propiedad perfecta para ti",
      filters: "Filtros",
      price_range: "Rango de precio",
      min_bedrooms: "Habitaciones mín.",
      min_bathrooms: "Baños mín.",
      features: "Características",
      heating: "Calefacción",
      pool: "Piscina",
      garage: "Garaje",
      air_conditioning: "Aire acondicionado",
      elevator: "Ascensor",
      terrace: "Terraza",
      garden: "Jardín",
      any: "Cualquiera",
      operation_all: "Todas",
      type_all: "Todos los tipos",
      managed_all: "Todos",
      featured: "Propiedades destacadas",
      featured_desc: "Descubre nuestras mejores propiedades seleccionadas especialmente para ti",
      search_results: "Resultados de búsqueda",
      search_results_desc: "Se encontraron {count} propiedades que coinciden con tu búsqueda",
      show_featured: "Ver propiedades destacadas",
      no_results: "No se encontraron propiedades con los criterios seleccionados",
      no_results_title: "No se encontraron propiedades",
      no_results_desc: "Intenta ajustar los filtros de búsqueda para encontrar más propiedades",
      view_all: "Ver todas las propiedades",
      type_apartment: "Apartamento",
      type_house: "Casa",
      type_loft: "Loft",
      type_studio: "Estudio",
      managed_nazari: "Gestionado por Nazarí",
      managed_other: "Gestionado por terceros",
      area_unit: "m²",
      more: "más",
      per_month: "/mes",
      operation_rent: "Alquiler",
      operation_sale: "Venta",
      view_details: "Ver detalles",
    },
    about: {
      title: "Acerca de",
      title_highlight: "Nazarí Homes",
      subtitle: "Conoce más sobre nuestra empresa y nuestro compromiso contigo",
      our_story: "Nuestra historia",
      story_p1:
        "Nazarí Homes nació en 2023 con la visión de ofrecer un servicio innovador de gestión de propiedades sin coste para los propietarios. Desde nuestros humildes comienzos, hemos crecido hasta convertirnos en una de las agencias inmobiliarias más respetadas y confiables de la región.",
      story_p2:
        "Nuestro compromiso con el servicio al cliente nos han permitido ayudar a miles de familias. Cada propiedad que gestionamos es tratada con el mismo cuidado y atención que si fuera nuestra propia casa.",
      our_values: "Nuestros valores",
      values_desc: "Los principios que nos guían en cada transacción y relación",
      commitment: {
        title: "Compromiso",
        description:
          "Nos comprometemos completamente con cada cliente, ofreciendo un servicio personalizado y dedicado.",
      },
      professionalism: {
        title: "Profesionalismo",
        description: "Mantenemos los más altos estándares profesionales en todas nuestras operaciones y relaciones.",
      },
      trust: {
        title: "Confianza",
        description: "Construimos relaciones duraderas basadas en la transparencia y la honestidad absoluta.",
      },
      excellence: {
        title: "Excelencia",
        description: "Buscamos la perfección en cada detalle, desde la presentación hasta el cierre de la venta.",
      },
      stats: {
        years: "Años de experiencia",
        properties: "Propiedades gestionadas",
        clients: "Clientes satisfechos",
        satisfaction: "Satisfacción del cliente",
      },
      our_team: "Nuestro equipo",
      team_desc: "Profesionales experimentados dedicados a hacer realidad tus sueños inmobiliarios",
      sales_team: {
        title: "Equipo de ventas",
        description:
          "Especialistas en ventas con años de experiencia en el mercado local, listos para encontrar la propiedad perfecta para ti.",
      },
      management_team: {
        title: "Equipo de gestión",
        description:
          "Expertos en gestión de propiedades que se encargan de mantener tus inversiones en perfectas condiciones.",
      },
      maintenance_team: {
        title: "Mantenimiento y reparaciones",
        description:
          "Equipo técnico especializado en la resolución de incidencias, mantenimiento preventivo y reparaciones urgentes para garantizar el confort de los inquilinos.",
      },
      renovation_team: {
        title: "Obras y reformas",
        description:
          "Profesionales en reformas integrales, rehabilitación de viviendas y proyectos de obra nueva para revalorizar tu propiedad.",
      },
      cta: {
        title: "¿Listo para encontrar tu hogar ideal?",
        description: "Ponte en contacto con nosotros y descubre cómo podemos ayudarte",
        contact: "Contáctanos",
        address: "Granada",
      },
    },
    services: {
      title: "Nuestros servicios",
      title_highlight: "profesionales",
      subtitle: "Ofrecemos servicios integrales para todas tus necesidades inmobiliarias",
      description: "Ofrecemos una amplia gama de servicios para ayudarte a encontrar la propiedad perfecta.",
      propertyManagement: "Gestión de propiedades",
      investmentAdvisory: "Asesoramiento de inversión",
      legalAssistance: "Asistencia legal",
      relocationServices: "Servicios de reubicación",
      what_can_we_do: "¿Qué podemos hacer por ti?",
      what_can_we_do_desc: "Descubre nuestros servicios especializados diseñados para cubrir todas tus necesidades",
      management: {
        title: "Gestión integral de propiedades",
        description: "Gestión completa de tu propiedad desde el primer día",
        feature1: "Mantenimiento preventivo y correctivo",
        feature2: "Gestión de inquilinos y contratos",
        feature3: "Reportes mensuales detallados",
        feature4: "Atención 24/7 para emergencias",
      },
      rental: {
        title: "Alquiler de propiedades",
        description: "Encuentra el inquilino perfecto para tu propiedad",
        feature1: "Evaluación de solvencia de inquilinos",
        feature2: "Marketing profesional de la propiedad",
        feature3: "Gestión de visitas y negociación",
        feature4: "Contratos legales y seguros",
      },
      renovation: {
        title: "Obras y reformas",
        description: "Servicios integrales de construcción y rehabilitación de inmuebles",
        feature1: "Reformas integrales de viviendas",
        feature2: "Rehabilitación de edificios",
        feature3: "Proyectos de obra nueva",
        feature4: "Presupuestos personalizados sin compromiso",
      },
      support: {
        title: "Soporte 24/7",
        description: "Estamos aquí cuando nos necesites",
        feature1: "Atención telefónica permanente",
        feature2: "Servicio de emergencias",
        feature3: "Mantenimiento urgente",
        feature4: "Consultas online",
      },
      tenants: {
        title: "Servicios para inquilinos",
        description: "Facilitamos tu experiencia como inquilino",
        feature1: "Búsqueda personalizada de propiedades",
        feature2: "Gestión de depósitos y garantías",
        feature3: "Mantenimiento incluido",
        feature4: "Comunicación directa con propietarios",
      },
      maintenance: {
        title: "Mantenimiento especializado",
        description: "Mantenemos tu propiedad en perfectas condiciones",
        feature1: "Inspecciones regulares programadas",
        feature2: "Reparaciones rápidas y eficientes",
        feature3: "Red de profesionales cualificados",
        feature4: "Presupuestos transparentes",
      },
      cta: {
        title: "¿Necesitas alguno de nuestros servicios?",
        description: "Contacta con nosotros para una consulta personalizada y gratuita",
        contact_now: "Contactar ahora",
        call_directly: "Llamar directamente",
      },
    },
    features: {
      title: "Características destacadas",
      modernDesign: "Diseño moderno",
      primeLocation: "Ubicación privilegiada",
      stunningViews: "Vistas impresionantes",
      privatePool: "Piscina privada",
      spaciousLayout: "Distribución espaciosa",
      highQualityFinishes: "Acabados de alta calidad",
    },
    testimonials: {
      title: "Testimonios",
      johnDoe: "Excelente servicio y atención personalizada. ¡Encontraron la casa de mis sueños!",
      janeSmith: "Profesionales y muy atentos a nuestras necesidades. ¡Recomendables al 100%!",
    },
    contact: {
      title: "Contáctanos",
      subtitle: "Ponte en contacto con nosotros para cualquier consulta",
      description: "Ponte en contacto con nosotros para cualquier consulta o para agendar una visita.",
      operation_area: "Área de operación",
      operation_zone: "Zona de operación",
      granada_province: "Provincia de Granada",
      no_physical_office: "No disponemos de oficina física, trabajamos visitando las propiedades",
      whatsapp_text: "Contáctanos por WhatsApp",
      whatsapp_message: "Hola, me gustaría obtener más información sobre sus servicios inmobiliarios.",
      form_title: "Formulario de contacto",
      form_subtitle: "Déjanos tu consulta y te responderemos lo antes posible",
      property_address: "Dirección del inmueble",
      name: "Nombre",
      surname: "Apellidos",
      email: "Correo electrónico",
      phone: "Teléfono",
      message: "Mensaje",
      privacy_text: "Acepto el tratamiento de mis datos conforme a la",
      privacy_policy: "política de privacidad",
      privacy_error: "Debes aceptar la política de privacidad para continuar",
      form_sent: "Formulario enviado",
      form_sent_desc: "Tu mensaje ha sido enviado correctamente. Te responderemos en breve.",
      send_button: "Enviar mensaje",
      send: "Enviar mensaje",
      address: "Dirección",
      emailAddress: "Correo electrónico",
    },
    footer: {
      company_description:
        "Nazarí Homes, tu agencia inmobiliaria de confianza. Especialistas en venta y alquiler de propiedades excepcionales.",
      quick_links: "Enlaces rápidos",
      services_section: "Servicios",
      contact_section: "Contacto",
      rental_properties: "Propiedades en alquiler",
      sale_properties: "Propiedades en venta",
      free_valuation: "Valoración gratuita",
      legal_advice: "Obras y reformas. Presupuestos sin compromiso",
      address: "Granada",
      phone: "+34 624 567 853",
      email: "info@nazarihomes.com",
      aboutUs: "Acerca de nosotros",
      contactUs: "Contáctanos",
      privacyPolicy: "Política de privacidad",
      termsOfService: "Términos de servicio",
      copyright: "Derechos de autor © 2026 Nazarí Homes. Todos los derechos reservados.",
    },
    account: {
      login: "Iniciar Sesión",
      register: "Crear Cuenta",
      loginDescription: "Accede a tu cuenta para continuar",
      registerDescription: "Crea tu cuenta para comenzar",
      continueWithGoogle: "Continuar con Google",
      registerWithGoogle: "Registrarse con Google",
      or: "o",
      fullName: "Nombre completo",
      enterName: "Ingresa tu nombre",
      email: "Correo electrónico",
      enterEmail: "Ingresa tu email",
      password: "Contraseña",
      enterPassword: "Ingresa tu contraseña",
      confirmPassword: "Confirmar contraseña",
      confirmPasswordPlaceholder: "Confirma tu contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      loginButton: "Iniciar Sesión",
      registerButton: "Crear Cuenta",
      noAccount: "¿No tienes cuenta?",
      hasAccount: "¿Ya tienes cuenta?",
      createAccount: "Crear cuenta",
      loginHere: "Inicia sesión aquí",
      loginRequired: "Debes iniciar sesión para acceder a esta funcionalidad",
      logout: "Cerrar sesión",
      myAccount: "Mi cuenta",
      myProperties: "Mis propiedades",
      favorites: "Favoritos",
      profile: "Perfil",
      uploadAvatar: "Subir avatar",
      changeAvatar: "Cambiar avatar",
      saveChanges: "Guardar cambios",
      cancel: "Cancelar",
      accessAccount: "Accede a tu cuenta",
      accountAccess: "Acceso a cuenta",
      authenticationRequired: "Autenticación requerida",
    },
    // Property detail page translations
    property: {
      not_found: "Propiedad no encontrada",
      back_to_properties: "Volver a propiedades",
      apartment_description:
        "Hermoso y moderno apartamento con todas las comodidades que necesitas para una vida cómoda.",
      house_description: "Casa espaciosa con jardín, perfecta para familias que buscan comodidad y tranquilidad.",
      loft_description:
        "Loft moderno con diseño industrial, ideal para quienes buscan un estilo de vida contemporáneo.",
      studio_description: "Estudio acogedor y funcional, perfecto para jóvenes profesionales o estudiantes.",
      default_description: "Excelente propiedad con grandes características y ubicación privilegiada.",
      wifi: "WiFi",
      air_conditioning: "Aire acondicionado",
      tv: "TV",
      parking: "Parking",
      per_month: "/mes",
      view_number: "Vista {{number}}",
      reference: "Ref",
      bedrooms: "Habitaciones",
      bathrooms: "Baños",
      area_label: "Área",
      description: "Descripción",
      location: "Ubicación",
      area_info: "Información del área",
      area_description: "Excelente zona con todos los servicios cerca, bien comunicada por transporte público.",
      features: "Características",
      elevator: "Ascensor",
      balcony: "Balcón",
      heating: "Calefacción",
      terrace: "Terraza",
      built_in_wardrobes: "Armarios empotrados",
      equipped_kitchen: "Cocina equipada",
      services: "Servicios y comodidades",
      additional_info: "Información adicional",
      transport: "Transporte",
      transport_description: "Excelente conexión de transporte público con autobuses regulares al centro de la ciudad.",
      neighborhood: "Barrio",
      neighborhood_description: "Zona residencial tranquila con todas las comodidades necesarias a poca distancia.",
      nearby_services: "Servicios cercanos",
      nearby_services_description: "Supermercados, farmacias, colegios y centros médicos en un radio de 500 metros.",
      real_estate_agent: "",
      senior_agent: "Asesor Inmobiliario",
      call: "Llamar",
      appointment: "Cita",
      whatsapp_chat: "Chat WhatsApp",
      whatsapp_description:
        "Contáctanos directamente por WhatsApp para obtener información inmediata sobre esta propiedad. Agencia: {{agency}}",
      quick_messages: "Mensajes rápidos",
      custom_message_placeholder: "Escribe un mensaje personalizado...",
      open_whatsapp: "Abrir WhatsApp",
      quick_response: "Respuesta rápida",
      reserve_property: "Reservar propiedad",
      reservation_description:
        "Completa el formulario de reserva para asegurar esta propiedad. Se requiere contrato firmado y pago inicial.",
      full_name: "Nombre completo",
      full_name_placeholder: "Ingresa tu nombre completo",
      email: "Correo electrónico",
      email_placeholder: "tu@email.com",
      phone: "Teléfono",
      phone_placeholder: "+34 xxx xxx xxx",
      dni_nie: "DNI/NIE",
      dni: "DNI/NIE",
      dni_placeholder: "12345678X",
      signed_contract: "Contrato firmado",
      upload_contract: "Subir contrato",
      change_pdf: "Cambiar PDF",
      proceed_payment: "Proceder al pago",
      secure_payment: "Pago seguro",
      request_info: "Solicitar información",
      contact_inquiry: "Consulta de contacto",
      inquiry_description:
        "Envíanos tus preguntas sobre esta propiedad y te responderemos en la mayor brevedad posible.",
      your_name: "Tu nombre",
      your_email: "Tu email",
      your_phone: "Tu teléfono",
      your_message: "Tu mensaje",
      send_inquiry: "Enviar consulta",
      whatsapp_default_message:
        "¡Hola! Estoy interesado/a en la propiedad {{title}} (Ref: {{reference}}) ubicada en {{location}} por {{price}}. ¿Podrían proporcionarme más información?",
      quick_message_visit:
        "¡Hola! Estoy interesado/a en visitar la propiedad {{title}} (Ref: {{reference}}) en {{location}}.",
      quick_message_available: "¡Hola! ¿La propiedad Ref: {{reference}} sigue disponible por {{price}}?",
      quick_message_schedule:
        "¡Hola! Me gustaría agendar una visita para la propiedad Ref: {{reference}} en {{location}}.",
      quick_message_price_info:
        "¡Hola! ¿Podrían proporcionar más información sobre el precio {{price}} de la propiedad Ref: {{reference}}?",
    },
    // Add favorites translations
    favorites: {
      title: "Mis Favoritos",
      no_favorites: "No tienes propiedades favoritas",
      count_single: "1 propiedad favorita",
      count_multiple: "{count} propiedades favoritas",
      clear_all: "Limpiar Todo",
      confirm_clear_title: "¿Confirmar limpiar favoritos?",
      confirm_clear_desc: "Esta acción eliminará todas las propiedades de tu lista de favoritos. No se puede deshacer.",
      cancel: "Cancelar",
      delete_all: "Eliminar Todo",
      empty_title: "No hay favoritos aún",
      empty_desc: "Las propiedades que marques como favoritas aparecerán aquí",
    },
    // Add privacy policy translations
    privacy: {
      title: "Política de Privacidad",
      subtitle: "Información sobre el tratamiento de datos personales",
      intro_p1:
        "La presente Política de Privacidad establece los términos en que Nazarí Homes utiliza y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web.",
      intro_p2:
        "Esta compañía está comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de información personal con la cual usted pueda ser identificado, lo hacemos asegurando que sólo se empleará de acuerdo con los términos de este documento.",
      intro_p3:
        "Sin embargo esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta página para asegurarse que está de acuerdo con dichos cambios. Si tienes alguna pregunta sobre esta política, puedes contactarnos en:",
      who_we_are: "¿Quiénes somos?",
      who_we_are_p1: "Nuestra dirección web es:",
      who_we_are_p1_cont:
        ". Somos una inmobiliaria especializada en la venta y alquiler de propiedades en Granada y sus alrededores.",
      who_we_are_p2: "Nazarí Homes es una empresa comprometida con brindar el mejor servicio a nuestros clientes.",
      who_we_are_p3:
        "Operamos bajo los más altos estándares de transparencia y profesionalidad en el sector inmobiliario.",
      limitations: "Limitaciones",
      limitations_p1:
        "En ningún caso seremos responsables por cualquier daño incluyendo pero no limitándose a, daños directos, indirectos, casuales, fortuitos o consecuentes, que resulten del uso o la imposibilidad de usar los materiales en este sitio, aún cuando hayamos sido informados de la posibilidad de tales daños.",
      data_purpose: "Finalidad de los datos",
      data_purpose_p1:
        "Todos los datos personales que nos proporciones serán utilizados únicamente para los fines relacionados con nuestros servicios inmobiliarios.",
      data_purpose_p2: "No utilizaremos tu información personal para fines distintos a los aquí especificados.",
      what_data: "¿Qué datos recopilamos?",
      what_data_p1:
        "Podemos recopilar la siguiente información: nombre completo, información de contacto incluyendo dirección de correo electrónico, información demográfica como código postal, preferencias e intereses, y otra información relevante para encuestas de satisfacción del cliente.",
      what_data_p2:
        "También podemos recopilar información sobre tu actividad en nuestro sitio web, incluyendo las propiedades que visualizas y las consultas que realizas.",
      what_data_p3:
        "Los datos de navegación se recopilan de forma anónima con fines estadísticos para mejorar nuestros servicios.",
      why_use_data: "¿Por qué utilizamos los datos?",
      why_use_data_p1:
        "Requerimos esta información para entender tus necesidades y brindarte un mejor servicio, y en particular por las siguientes razones: mantenimiento de registros internos, mejoramiento de nuestros productos y servicios, y envío periódico de correos promocionales sobre nuevas propiedades y ofertas especiales.",
      why_use_data_p2:
        "De vez en cuando, también podemos utilizar tu información para contactarte para fines de investigación de mercado.",
      data_retention: "Retención de datos",
      data_retention_p1:
        "Conservaremos tu información personal mientras mantengas una cuenta activa con nosotros o según sea necesario para brindarte nuestros servicios. Si deseas que eliminemos tu información, puedes contactarnos en ",
      data_retention_p1_cont: " y procesaremos tu solicitud de acuerdo con las leyes aplicables.",
      data_retention_p2:
        "También podemos conservar y utilizar tu información según sea necesario para cumplir con nuestras obligaciones legales, resolver disputas y hacer cumplir nuestros acuerdos.",
      data_retention_p3:
        "Los datos de navegación anónimos pueden conservarse por períodos más largos con fines estadísticos.",
      data_sharing: "Compartir datos",
      data_sharing_p1:
        "No vendemos, intercambiamos ni transferimos de ninguna manera tu información personal a terceros sin tu consentimiento.",
      data_sharing_p2:
        "Esto no incluye a terceros de confianza que nos ayudan a operar nuestro sitio web, realizar nuestro negocio o brindar servicios, siempre que esas partes acuerden mantener confidencial esta información.",
      data_sharing_p3:
        "También podemos divulgar tu información cuando creamos de buena fe que la divulgación es apropiada para cumplir con la ley, hacer cumplir las políticas de nuestro sitio o proteger nuestros derechos, propiedad o seguridad. Para cualquier consulta sobre el tratamiento de datos, contacta:",
      your_rights: "Tus derechos",
      your_rights_p1:
        "Tienes derecho a solicitar información sobre los datos personales que tenemos sobre ti, así como a solicitar la corrección, actualización o eliminación de dichos datos. Puedes ejercer estos derechos contactándonos en ",
      your_rights_li1: "Derecho de acceso: puedes solicitar copias de tus datos personales.",
      your_rights_li2:
        "Derecho de rectificación: puedes solicitar que corrijamos cualquier información que consideres inexacta.",
      your_rights_li3:
        "Derecho de supresión: puedes solicitar que eliminemos tus datos personales bajo ciertas condiciones.",
      your_rights_li4:
        "Derecho a la portabilidad: puedes solicitar que transfiramos los datos que hemos recopilado a otra organización o directamente a ti.",
      policy_changes: "Cambios en la política",
      policy_changes_p1:
        "Nazarí Homes se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.",
      policy_changes_p2:
        "Te notificaremos sobre cualquier cambio publicando la nueva Política de Privacidad en esta página.",
      policy_changes_p3:
        "Te recomendamos revisar esta política periódicamente para estar informado sobre cómo protegemos tu información.",
    },
    cookies: {
      title: "Uso de Cookies",
      description:
        "Utilizamos cookies para mejorar tu experiencia, personalizar contenido y recordar tus preferencias como los favoritos. Al continuar navegando, aceptas nuestro uso de cookies.",
      privacy_policy: "Política de Privacidad",
      accept: "Aceptar",
      reject: "Rechazar",
    },
    tenant_section: {
      title: "¿Eres inquilino?",
      subtitle:
        "Reporta incidencias de tu alquiler de forma rápida y sencilla. Solo necesitas el código de acceso que te proporcionó tu inmobiliaria.",
      step1_title: "Identifícate",
      step1_desc: "Introduce el código UUID que te entregaron al firmar tu contrato de alquiler.",
      step2_title: "Reporta incidencias",
      step2_desc: "Describe el problema y sube fotos para que tu propietario pueda gestionarlo rápidamente.",
      step3_title: "¿Algo urgente?",
      step3_desc: "Usa nuestro enlace de WhatsApp para comunicarte directamente con tu inmobiliaria.",
      cta: "Acceder como inquilino",
    },
  },
  en: {
    nav: {
      home: "Home",
      properties: "Properties",
      services: "Services",
      about: "About",
      contact: "Contact",
      favorites: "Favorites",
      account: "Account",
    },
    common: {
      language: "Language",
      search: "Search",
      address: "Address",
      all: "All",
      bedrooms: "Bedrooms",
      bathrooms: "Bathrooms",
      area: "Area",
      price: "Price",
      applyFilters: "Apply filters",
      resetFilters: "Reset filters",
      loadMore: "Load more",
      noPropertiesFound: "No properties found with the current search criteria.",
      details: "Details",
      description: "Description",
      amenities: "Amenities",
      location: "Location",
      contactUs: "Contact us",
      disclaimer: "Disclaimer",
      disclaimerText:
        "Property information is provided as a guide only and does not constitute a contractual offer. All representations including dimensions, floor plan details and availability are subject to change and should be independently verified.",
      share: "Share",
      addToFavorites: "Add to favorites",
      removeFromFavorites: "Remove from favorites",
      relatedProperties: "Related properties",
      map: "Map",
      streetView: "Street View",
      virtualTour: "Virtual Tour",
      scheduleVisit: "Schedule Visit",
      mortgageCalculator: "Mortgage Calculator",
      cancel: "Cancel",
      back: "Back",
    },
    hero: {
      title: "Find your ideal home",
      title_highlight: "on the Tropical Coast",
      subtitle: "Discover the best properties on the Tropical Coast",
      searchPlaceholder: "What are you looking for?",
    },
    search: {
      location_placeholder: "Search by location...",
      property_type: "Property type",
      property_type_any: "Any type",
      property_type_apartment: "Apartment",
      property_type_house: "House",
      property_type_loft: "Loft",
      property_type_studio: "Studio",
      operation: "Operation",
      operation_any: "Any",
      operation_rent: "Rent",
      operation_sale: "Sale",
      managed_by: "Managed by",
      managed_by_any: "Any",
      managed_by_nazari: "Nazarí Homes",
      managed_by_other: "Others",
      search_btn: "Search",
    },
    location: {
      search_text: "Search location",
      search_location: "Search by location",
      search_by_location: "Search by location",
      search_address: "Address",
      address_placeholder: "Enter an address...",
      search_radius: "Search radius",
      radius_500m: "500 meters",
      radius_1km: "1 kilometer",
      radius_2km: "2 kilometers",
      radius_5km: "5 kilometers",
      radius_10km: "10 kilometers",
      radius_10km_plus: "10+ kilometers",
      my_location: "My location",
      apply_location: "Apply location",
    },
    stats: {
      properties: "Available properties",
      clients: "Satisfied clients",
      success_rate: "Success rate",
    },
    properties: {
      page_title: "properties found",
      search_placeholder: "Search by title or location...",
      results_subtitle: "Find the perfect property for you",
      filters: "Filters",
      price_range: "Price range",
      min_bedrooms: "Min. bedrooms",
      min_bathrooms: "Min. bathrooms",
      features: "Features",
      heating: "Heating",
      pool: "Pool",
      garage: "Garage",
      air_conditioning: "Air conditioning",
      elevator: "Elevator",
      terrace: "Terrace",
      garden: "Garden",
      any: "Any",
      operation_all: "All",
      type_all: "All types",
      managed_all: "All",
      featured: "Featured properties",
      featured_desc: "Discover our best properties specially selected for you",
      search_results: "Search results",
      search_results_desc: "Found {count} properties matching your search",
      show_featured: "Show featured properties",
      no_results: "No properties found with the selected criteria",
      no_results_title: "No properties found",
      no_results_desc: "Try adjusting your search filters to find more properties",
      view_all: "View all properties",
      type_apartment: "Apartment",
      type_house: "House",
      type_loft: "Loft",
      type_studio: "Studio",
      managed_nazari: "Managed by Nazarí",
      managed_other: "Managed by third parties",
      area_unit: "m²",
      more: "more",
      per_month: "/month",
      operation_rent: "Rent",
      operation_sale: "Sale",
      view_details: "View details",
    },
    about: {
      title: "About",
      title_highlight: "Nazarí Homes",
      subtitle: "Learn more about our company and our commitment to you",
      our_story: "Our story",
      story_p1:
        "Nazarí Homes was born in 2009 with the vision of revolutionizing the real estate market on the Tropical Coast of Granada. From our humble beginnings, we have grown to become one of the most respected and trusted real estate agencies in the region.",
      story_p2:
        "Our passion for exceptional properties and our commitment to customer service have allowed us to help thousands of families find their ideal home. Every property we manage is treated with the same care and attention as if it were our own home.",
      our_values: "Our values",
      values_desc: "The principles that guide us in every transaction and relationship",
      commitment: {
        title: "Commitment",
        description: "We are fully committed to each client, offering personalized and dedicated service.",
      },
      professionalism: {
        title: "Professionalism",
        description: "We maintain the highest professional standards in all our operations and relationships.",
      },
      trust: {
        title: "Trust",
        description: "We build lasting relationships based on transparency and absolute honesty.",
      },
      excellence: {
        title: "Excellence",
        description: "We seek perfection in every detail, from presentation to closing the sale.",
      },
      stats: {
        years: "Years of experience",
        properties: "Managed properties",
        clients: "Satisfied clients",
        satisfaction: "Customer satisfaction",
      },
      our_team: "Our team",
      team_desc: "Experienced professionals dedicated to making your real estate dreams come true",
      sales_team: {
        title: "Sales team",
        description:
          "Sales specialists with years of experience in the local market, ready to find the perfect property for you.",
      },
      management_team: {
        title: "Management team",
        description: "Property management experts who take care of keeping your investments in perfect condition.",
      },
      maintenance_team: {
        title: "Maintenance & Repairs",
        description:
          "Technical team specialised in incident resolution, preventive maintenance and urgent repairs to ensure tenant comfort.",
      },
      renovation_team: {
        title: "Construction & Renovations",
        description:
          "Professionals in comprehensive renovations, housing rehabilitation and new construction projects to increase your property value.",
      },
      cta: {
        title: "Ready to find your ideal home?",
        description: "Contact us and discover how we can help you",
        contact: "Contact us",
        address: "Granada",
      },
    },
    services: {
      title: "Our services",
      title_highlight: "professional",
      subtitle: "We offer comprehensive services for all your real estate needs",
      description: "We offer a wide range of services to help you find the perfect property.",
      propertyManagement: "Property Management",
      investmentAdvisory: "Investment Advisory",
      legalAssistance: "Legal Assistance",
      relocationServices: "Relocation Services",
      what_can_we_do: "What can we do for you?",
      what_can_we_do_desc: "Discover our specialized services designed to cover all your needs",
      management: {
        title: "Comprehensive property management",
        description: "Complete management of your property from day one",
        feature1: "Preventive and corrective maintenance",
        feature2: "Tenant and contract management",
        feature3: "Detailed monthly reports",
        feature4: "24/7 emergency assistance",
      },
      rental: {
        title: "Property rental",
        description: "Find the perfect tenant for your property",
        feature1: "Tenant solvency assessment",
        feature2: "Professional property marketing",
        feature3: "Visit management and negotiation",
        feature4: "Legal contracts and insurance",
      },
      renovation: {
        title: "Construction & Renovations",
        description: "Comprehensive construction and property rehabilitation services",
        feature1: "Full home renovations",
        feature2: "Building rehabilitation",
        feature3: "New construction projects",
        feature4: "Free personalized quotes",
      },
      support: {
        title: "24/7 Support",
        description: "We are here when you need us",
        feature1: "Permanent phone assistance",
        feature2: "Emergency service",
        feature3: "Urgent maintenance",
        feature4: "Online consultations",
      },
      tenants: {
        title: "Tenant services",
        description: "We facilitate your experience as a tenant",
        feature1: "Personalized property search",
        feature2: "Deposit and guarantee management",
        feature3: "Maintenance included",
        feature4: "Direct communication with owners",
      },
      maintenance: {
        title: "Specialized maintenance",
        description: "We keep your property in perfect condition",
        feature1: "Scheduled regular inspections",
        feature2: "Fast and efficient repairs",
        feature3: "Network of qualified professionals",
        feature4: "Transparent budgets",
      },
      cta: {
        title: "Need any of our services?",
        description: "Contact us for a personalized and free consultation",
        contact_now: "Contact now",
        call_directly: "Call directly",
      },
    },
    features: {
      title: "Featured characteristics",
      modernDesign: "Modern design",
      primeLocation: "Prime location",
      stunningViews: "Stunning views",
      privatePool: "Private pool",
      spaciousLayout: "Spacious layout",
      highQualityFinishes: "High quality finishes",
    },
    testimonials: {
      title: "Testimonials",
      johnDoe: "Excellent service and personalized attention. They found the house of my dreams!",
      janeSmith: "Professional and very attentive to our needs. 100% recommended!",
    },
    contact: {
      title: "Contact us",
      subtitle: "Get in touch with us for any questions",
      description: "Get in touch with us for any questions or to schedule a visit.",
      operation_area: "Operation area",
      operation_zone: "Operation zone",
      granada_province: "Granada Province",
      no_physical_office: "We do not have a physical office, we work by visiting properties",
      whatsapp_text: "Contact us via WhatsApp",
      whatsapp_message: "Hello, I would like to get more information about your real estate services.",
      form_title: "Contact form",
      form_subtitle: "Leave us your inquiry and we will respond as soon as possible",
      property_address: "Property address",
      name: "Name",
      surname: "Surname",
      email: "Email",
      phone: "Phone",
      message: "Message",
      privacy_text: "I accept the processing of my data according to the",
      privacy_policy: "privacy policy",
      privacy_error: "You must accept the privacy policy to continue",
      form_sent: "Form sent",
      form_sent_desc: "Your message has been sent successfully. We will respond shortly.",
      send_button: "Send message",
      send: "Send message",
      address: "Address",
      emailAddress: "Email Address",
    },
    footer: {
      company_description:
        "Nazarí Homes, your trusted real estate agency on the Tropical Coast. Specialists in sale and rental of exceptional properties.",
      quick_links: "Quick links",
      services_section: "Services",
      contact_section: "Contact",
      rental_properties: "Rental properties",
      sale_properties: "Properties for sale",
      free_valuation: "Free valuation",
      legal_advice: "Legal advice",
      address: "Granada",
      phone: "+34 624 567 853",
      email: "info@nazarihomes.com",
      aboutUs: "About us",
      contactUs: "Contact us",
      privacyPolicy: "Privacy policy",
      termsOfService: "Terms of service",
      copyright: "Copyright © 2026 Nazarí Homes. All rights reserved.",
    },
    account: {
      login: "Sign In",
      register: "Create Account",
      loginDescription: "Access your account to continue",
      registerDescription: "Create your account to get started",
      continueWithGoogle: "Continue with Google",
      registerWithGoogle: "Sign up with Google",
      or: "or",
      fullName: "Full name",
      enterName: "Enter your name",
      email: "Email",
      enterEmail: "Enter your email",
      password: "Password",
      enterPassword: "Enter your password",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Confirm your password",
      forgotPassword: "Forgot your password?",
      loginButton: "Sign In",
      registerButton: "Create Account",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      createAccount: "Create account",
      loginHere: "Sign in here",
    },
    // Property detail page translations
    property: {
      not_found: "Property not found",
      back_to_properties: "Back to Properties",
      apartment_description: "Beautiful and modern apartment with all the amenities you need for comfortable living.",
      house_description: "Spacious house with garden, perfect for families looking for comfort and tranquility.",
      loft_description: "Modern loft with industrial design, ideal for those seeking a contemporary lifestyle.",
      studio_description: "Cozy and functional studio, perfect for young professionals or students.",
      default_description: "Excellent property with great features and privileged location.",
      wifi: "WiFi",
      air_conditioning: "Air conditioning",
      tv: "TV",
      parking: "Parking",
      per_month: "/month",
      view_number: "View {{number}}",
      reference: "Ref",
      bedrooms: "Bedrooms",
      bathrooms: "Bathrooms",
      area_label: "Area",
      description: "Description",
      location: "Location",
      area_info: "Area Information",
      area_description: "Excellent area with all services nearby, well connected by public transport.",
      features: "Features",
      elevator: "Elevator",
      balcony: "Balcony",
      heating: "Heating",
      terrace: "Terrace",
      built_in_wardrobes: "Built-in wardrobes",
      equipped_kitchen: "Equipped kitchen",
      services: "Services & Amenities",
      additional_info: "Additional Information",
      transport: "Transport",
      transport_description: "Excellent public transport connection with regular buses to the city center.",
      neighborhood: "Neighborhood",
      neighborhood_description: "Quiet residential area with all necessary amenities within walking distance.",
      nearby_services: "Nearby Services",
      nearby_services_description: "Supermarkets, pharmacies, schools and medical centers within a 500-meter radius.",
      real_estate_agent: "Real Estate Advisor",
      senior_agent: "Real Estate Advisor",
      call: "Call",
      appointment: "Appointment",
      whatsapp_chat: "WhatsApp Chat",
      whatsapp_description:
        "Contact us directly via WhatsApp for immediate information about this property. Agency: {{agency}}",
      quick_messages: "Quick Messages",
      custom_message_placeholder: "Write a custom message...",
      open_whatsapp: "Open WhatsApp",
      quick_response: "Quick Response",
      reserve_property: "Reserve Property",
      reservation_description:
        "Complete the reservation form to secure this property. Signed contract and initial payment required.",
      full_name: "Full Name",
      full_name_placeholder: "Enter your full name",
      email: "Email",
      email_placeholder: "your@email.com",
      phone: "Phone",
      phone_placeholder: "+34 xxx xxx xxx",
      dni_nie: "DNI/NIE",
      dni: "DNI/NIE",
      dni_placeholder: "12345678X",
      signed_contract: "Signed Contract",
      upload_contract: "Upload Contract",
      change_pdf: "Change PDF",
      proceed_payment: "Proceed to Payment",
      secure_payment: "Secure Payment",
      request_info: "Request Information",
      contact_inquiry: "Contact Inquiry",
      inquiry_description: "Send us your questions about this property and we will respond as soon as possible.",
      your_name: "Your Name",
      your_email: "Your Email",
      your_phone: "Your Phone",
      your_message: "Your Message",
      send_inquiry: "Send Inquiry",
      whatsapp_default_message:
        "Hello! I'm interested in the property {{title}} (Ref: {{reference}}) located in {{location}} for {{price}}. Could you provide me with more information?",
      quick_message_visit:
        "Hello! I'm interested in visiting the property {{title}} (Ref: {{reference}}) in {{location}}.",
      quick_message_available: "Hello! Is the property Ref: {{reference}} still available for {{price}}?",
      quick_message_schedule:
        "Hello! I would like to schedule a visit for the property Ref: {{reference}} in {{location}}.",
      quick_message_price_info:
        "Hello! Could you provide more information about the price {{price}} for property Ref: {{reference}}?",
    },
    // Add favorites translations
    favorites: {
      title: "My Favorites",
      no_favorites: "You have no favorite properties",
      count_single: "1 favorite property",
      count_multiple: "{count} favorite properties",
      clear_all: "Clear All",
      confirm_clear_title: "Confirm clear favorites?",
      confirm_clear_desc: "This action will remove all properties from your favorites list. This cannot be undone.",
      cancel: "Cancel",
      delete_all: "Delete All",
      empty_title: "No favorites yet",
      empty_desc: "Properties you mark as favorites will appear here",
    },
    // Add privacy policy translations
    privacy: {
      title: "Privacy Policy",
      subtitle: "Information about personal data processing",
      intro_p1:
        "This Privacy Policy establishes the terms in which Nazarí Homes uses and protects the information provided by its users when using its website.",
      intro_p2:
        "This company is committed to the security of its users' data. When we ask you to fill out personal information fields with which you can be identified, we do so ensuring that it will only be used in accordance with the terms of this document.",
      intro_p3:
        "However, this Privacy Policy may change over time or be updated, so we recommend and emphasize reviewing this page continuously to ensure you agree with such changes. If you have any questions about this policy, you can contact us at:",
      who_we_are: "Who we are?",
      who_we_are_p1: "Our website address is:",
      who_we_are_p1_cont:
        ". We are a real estate agency specialized in the sale and rental of properties in Granada and its surroundings.",
      who_we_are_p2:
        "Nazarí Homes is a company committed to providing the best service to our clients in the search for their ideal home.",
      who_we_are_p3:
        "We operate under the highest standards of transparency and professionalism in the real estate sector.",
      limitations: "Limitations",
      limitations_p1:
        "In no event shall we be liable for any damages including but not limited to, direct, indirect, incidental, punitive or consequential damages, arising from the use or inability to use the materials on this site, even if we have been advised of the possibility of such damages.",
      data_purpose: "Purpose of data",
      data_purpose_p1:
        "All personal data you provide us will be used only for purposes related to our real estate services.",
      data_purpose_p2: "We will not use your personal information for purposes other than those specified here.",
      what_data: "What data do we collect?",
      what_data_p1:
        "We may collect the following information: full name, contact information including email address, demographic information such as postal code, preferences and interests, and other information relevant to customer satisfaction surveys.",
      what_data_p2:
        "We may also collect information about your activity on our website, including the properties you view and the queries you make.",
      what_data_p3: "Navigation data is collected anonymously for statistical purposes to improve our services.",
      why_use_data: "Why do we use the data?",
      why_use_data_p1:
        "We require this information to understand your needs and provide you with a better service, and in particular for the following reasons: internal record keeping, improvement of our products and services, and periodic sending of promotional emails about new properties and special offers.",
      why_use_data_p2:
        "From time to time, we may also use your information to contact you for market research purposes.",
      data_retention: "Data retention",
      data_retention_p1:
        "We will retain your personal information as long as you maintain an active account with us or as necessary to provide you with our services. If you want us to delete your information, you can contact us at",
      data_retention_p1_cont: " and we will process your request in accordance with applicable laws.",
      data_retention_p2:
        "We may also retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.",
      data_retention_p3: "Anonymous navigation data may be retained for longer periods for statistical purposes.",
      data_sharing: "Data sharing",
      data_sharing_p1:
        "We do not sell, trade or otherwise transfer your personal information to third parties without your consent.",
      data_sharing_p2:
        "This does not include trusted third parties who assist us in operating our website, conducting our business, or providing services, as long as those parties agree to keep this information confidential.",
      data_sharing_p3:
        "We may also disclose your information when we believe in good faith that disclosure is appropriate to comply with the law, enforce our site policies, or protect our rights, property or safety. For any questions about data processing, contact:",
      your_rights: "Your rights",
      your_rights_p1:
        "You have the right to request information about the personal data we have about you, as well as to request the correction, updating or deletion of such data. You can exercise these rights by contacting us at",
      your_rights_li1: "Right of access: you can request copies of your personal data.",
      your_rights_li2:
        "Right of rectification: you can request that we correct any information you consider inaccurate.",
      your_rights_li3: "Right of erasure: you can request that we delete your personal data under certain conditions.",
      your_rights_li4:
        "Right to portability: you can request that we transfer the data we have collected to another organization or directly to you.",
      policy_changes: "Policy changes",
      policy_changes_p1: "Nazarí Homes reserves the right to change the terms of this Privacy Policy at any time.",
      policy_changes_p2: "We will notify you of any changes by posting the new Privacy Policy on this page.",
      policy_changes_p3:
        "We recommend reviewing this policy periodically to stay informed about how we protect your information.",
    },
    cookies: {
      title: "Cookie Usage",
      description:
        "We use cookies to improve your experience, personalize content and remember your preferences like favorites. By continuing to browse, you accept our use of cookies.",
      privacy_policy: "Privacy Policy",
      accept: "Accept",
      reject: "Reject",
    },
    tenant_section: {
      title: "Are you a tenant?",
      subtitle:
        "Report incidents in your rental quickly and easily. You only need the access code provided by your property manager.",
      step1_title: "Identify yourself",
      step1_desc: "Enter the UUID code given to you when you signed your rental contract.",
      step2_title: "Report incidents",
      step2_desc: "Describe the issue and upload photos so your landlord can handle it quickly.",
      step3_title: "Something urgent?",
      step3_desc: "Use our WhatsApp link to communicate directly with your property manager.",
      cta: "Access as tenant",
    },
  },
};

const LanguageContext = createContext<LanguageContextProps>({
  language: "es",
  setLanguage: () => {},
  t: (key: string) => key,
});

interface LanguageProviderProps {
  children: ReactNode;
}

const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string, params: Record<string, string | number> = {}): string => {
    const keys = key.split(".");
    let value: string | Translation | undefined = translations[language];

    for (const k of keys) {
      if (typeof value === "object" && value !== null && k in value) {
        value = value[k];
      } else {
        console.warn(`Translation key "${key}" not found in ${language}`);
        return key;
      }
    }

    if (typeof value === "string") {
      let translatedText = value;
      for (const paramKey in params) {
        translatedText = translatedText.replace(`{{${paramKey}}}`, String(params[paramKey]));
      }
      return translatedText;
    } else {
      console.warn(`Translation key "${key}" does not resolve to a string in ${language}`);
      return key;
    }
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};

const useLanguage = () => {
  return useContext(LanguageContext);
};

export { LanguageProvider, useLanguage };
