// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzkawijtocphmvrpoqfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6a2F3aWp0b2NwaG12cnBvcWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjQyOTUsImV4cCI6MjA2Nzk0MDI5NX0.2JnthwZ_Ph9wVCe3emdj3HIGaQHLutOoQft6qEEs3TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});